# Set the base image to Ubuntu
FROM continuumio/miniconda3

# File Author / Maintainer
MAINTAINER Thomas Schmelzer "thomas.schmelzer@lobnek.com"

# this is used to mock http for testing
RUN pip install httpretty nose coverage nose-timer

RUN conda install -q -y pandas=0.19.2 requests networkx

COPY ./pyaddepar /pyaddepar/pyaddepar
COPY ./test   /pyaddepar/test

WORKDIR /pyaddepar

CMD nosetests -w /pyaddepar/test --with-coverage --cover-html --cover-erase --cover-package=pyaddepar --cover-html-dir=/html-coverage --with-timer