# Set the base image to Ubuntu
FROM continuumio/miniconda3

# File Author / Maintainer
MAINTAINER Thomas Schmelzer "thomas.schmelzer@lobnek.com"

# this is used to mock http for testing
RUN pip install httpretty pytest pytest-cov pytest-html sphinx requests-mock

RUN conda install -q -y pandas=0.21 requests

COPY ./pyaddepar /pyaddepar/pyaddepar
COPY ./test   /pyaddepar/test

WORKDIR /pyaddepar

CMD py.test --cov=pyaddepar  --cov-report html:/html-coverage --cov-report term --html=/html-report/report.html test
