name: "book"

on:
- push

jobs:
  marimo:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.59

      - uses: tschm/cradle/actions/marimo@v0.1.59
        with:
          source_folder: book/marimo

  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.59

      - uses: tschm/cradle/actions/pdoc@v0.1.59
        with:
          source-folder: src/pyaddepar

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment"
        uses: tschm/cradle/actions/environment@v0.1.59

      - uses: tschm/cradle/actions/coverage@v0.1.59
        with:
          tests-folder: src/tests
          source-folder: src/pyaddepar
          coveralls: 'false'

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.59

      - uses: tschm/cradle/actions/jupyter@v0.1.59

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter, marimo]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v2.1.1
