name: "book"

on:
  push:
    branches:
      - main

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/pdoc@v1.4.0
        with:
          source-folder: 'pyaddepar'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/test@v1.4.0

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/jupyter@v1.4.0

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v1.4.0
