name: "book"

on:
  push:
    branches:
      - main

jobs:
  pdoc:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/pdoc@v2.0.0
        with:
          source-folder: 'pyaddepar'

  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/coverage@v2.0.0

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/jupyter@v2.0.0

  book:
    runs-on: "ubuntu-latest"
    needs: [test, pdoc, jupyter]

    permissions:
      contents: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/book@v2.0.0
