name: "book"

on:
  push:
    branches:
      - main

jobs:
  sphinx:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/sphinx@v1.3.0

  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/test@v1.3.0

  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/jupyter@v1.3.0

  book:
    runs-on: "ubuntu-latest"
    needs: [test, sphinx, jupyter]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@v1.3.0
